/**
 * Token build — generates the 3-tier CSS + typed TS from DTCG sources.
 *
 *   primitive/*.json   → :root  raw values          (--ds-*)
 *   semantic/base.json → :root  var() references     (--sem-*)
 *   semantic/brand.*   → [data-brand="…"] overrides  (only the diff)
 *   semantic/theme.*   → [data-theme="…"] overrides  (only the diff)
 *
 * Semantics keep the var() indirection (outputReferences) so overriding a
 * primitive — or swapping a brand/theme block — cascades at runtime.
 */
import StyleDictionary from 'style-dictionary';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const src = (p) => resolve(__dirname, 'src/design', p);
const OUT = 'libs/tokens/src/generated/';

// Only color / name transforms — dimensions & shadows pass through as authored.
const transforms = ['attribute/cti', 'name/kebab', 'color/css'];
const primitives = [src('primitive/color.json'), src('primitive/scale.json')];
const base = [...primitives, src('semantic/base.json')];

/** A CSS file scoped to `selector`, containing only tokens from `fromFile`. */
const cssFile = (destination, selector, fromFile, outputReferences = true) => ({
  destination,
  format: 'css/variables',
  filter: (t) => t.filePath.endsWith(fromFile),
  options: { selector, outputReferences, usesDtcg: true },
});

// Typed helper: flat map of semantic tokens → var() references.
StyleDictionary.registerFormat({
  name: 'ts/semantic-vars',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .filter((t) => t.path[0] === 'sem')
      .map((t) => `  '${t.path.slice(1).join('-')}': 'var(--${t.name})',`)
      .join('\n');
    return (
      '// AUTO-GENERATED by libs/tokens/build.mjs — do not edit.\n' +
      `export const tokens = {\n${entries}\n} as const;\n\n` +
      'export type TokenName = keyof typeof tokens;\n'
    );
  },
});

const build = (cfg) => new StyleDictionary(cfg).buildAllPlatforms();

// 1. Primitives + base semantics + typed export (:root)
await build({
  source: base,
  platforms: {
    css: {
      transforms,
      buildPath: OUT,
      files: [
        {
          destination: 'primitives.css',
          format: 'css/variables',
          filter: (t) => t.path[0] === 'ds',
          options: { selector: ':root', outputReferences: false, usesDtcg: true },
        },
        cssFile('semantic.base.css', ':root', 'base.json'),
        {
          destination: 'tokens.ts',
          format: 'ts/semantic-vars',
          filter: (t) => t.path[0] === 'sem',
          options: { usesDtcg: true },
        },
      ],
    },
  },
});

// 2. Corp brand overrides ([data-brand="corp"])
await build({
  source: [...base, src('semantic/brand.corp.json')],
  platforms: {
    css: {
      transforms,
      buildPath: OUT,
      files: [cssFile('semantic.brand-corp.css', '[data-brand="corp"]', 'brand.corp.json')],
    },
  },
});

// 3. Dark theme overrides ([data-theme="dark"])
await build({
  source: [...base, src('semantic/theme.dark.json')],
  platforms: {
    css: {
      transforms,
      buildPath: OUT,
      files: [cssFile('semantic.theme-dark.css', '[data-theme="dark"]', 'theme.dark.json')],
    },
  },
});

console.log('✓ tokens generated →', OUT);
